<?php
declare(strict_types=1);
require __DIR__ . '/../server/src/App.php';
$pdo = new PDO('sqlite::memory:', null, null, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC]);
$pdo->exec("CREATE TABLE projects (id INTEGER PRIMARY KEY, slug TEXT); INSERT INTO projects VALUES (1,'smoke');");
$pdo->exec('CREATE TABLE updates (id TEXT, project_id INTEGER, platform TEXT, runtime_version TEXT, channel TEXT, status TEXT, created_at TEXT, manifest_json TEXT, manifest_signature TEXT)');
$pdo->exec('CREATE TABLE directives (id INTEGER, project_id INTEGER, platform TEXT, runtime_version TEXT, channel TEXT, active INTEGER, created_at TEXT, body_json TEXT, signature TEXT)');
$bytes = '{"id":"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa","runtimeVersion":"1"}';
$sig = 'sig="test", keyid="main", alg="rsa-v1_5-sha256"';
$stmt = $pdo->prepare('INSERT INTO updates VALUES (?,1,?,?,?,?,?,?,?)');
$stmt->execute(['aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','ios','1','production','active','2026-09-23 00:00:00.000000',$bytes,$sig]);
$ref = new ReflectionClass(OtaApp::class);
$app = $ref->newInstanceWithoutConstructor();
foreach (['db'=>$pdo, 'base'=>'https://example.com/ota', 'storage'=>'/tmp', 'config'=>['default_channel'=>'production','signing_key_id'=>'main']] as $name=>$value) $ref->getProperty($name)->setValue($app,$value);
$method = $ref->getMethod('manifest');
$headers = $ref->getProperty('headers');
$headers->setValue($app,['expo-protocol-version'=>'1','expo-platform'=>'ios','expo-runtime-version'=>'1','accept'=>'multipart/mixed','expo-expect-signature'=>'sig, keyid="main", alg="rsa-v1_5-sha256"']);
ob_start(); $method->invoke($app,'smoke'); $response = ob_get_clean();
assert(str_contains($response, 'name="manifest"'));
assert(str_contains($response, 'expo-signature: '.$sig));
assert(str_contains($response, "\r\n\r\n".$bytes."\r\n"));
$headers->setValue($app,['expo-protocol-version'=>'1','expo-platform'=>'ios','expo-runtime-version'=>'2','accept'=>'multipart/mixed']);
ob_start(); $method->invoke($app,'smoke'); $response = ob_get_clean();
assert($response === '' && http_response_code() === 204);
$headers->setValue($app,['expo-protocol-version'=>'1','expo-platform'=>'ios','expo-runtime-version'=>'1','expo-channel-name'=>'preview','accept'=>'multipart/mixed']);
ob_start(); $method->invoke($app,'smoke'); $response = ob_get_clean();
assert($response === '' && http_response_code() === 204);
$headers->setValue($app,['expo-protocol-version'=>'1','expo-platform'=>'ios','expo-runtime-version'=>'1','expo-channel-name'=>'production','expo-current-update-id'=>'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','accept'=>'multipart/mixed']);
ob_start(); $method->invoke($app,'smoke'); $response = ob_get_clean();
assert($response === '' && http_response_code() === 204);
echo "PHP manifest routing OK\n";
